export { default as Box } from "./ink-runtime/components/Box.js";
export { default as Text } from "./ink-runtime/components/Text.js";
export { default as render } from "./ink-runtime/root.js";
export { default as useApp } from "./ink-runtime/hooks/use-app.js";
export { default as useInput } from "./ink-runtime/hooks/use-input.js";
export { default as useStdout } from "./ink-runtime/hooks/use-stdout.js";
export { default as useStdin } from "./ink-runtime/hooks/use-stdin.js";
export { AlternateScreen } from "./ink-runtime/components/AlternateScreen.js";
export { default as ScrollBox } from "./ink-runtime/components/ScrollBox.js";
export type { ScrollBoxHandle } from "./ink-runtime/components/ScrollBox.js";
